### ISSUE TITLE
Is there a record of build flags used

### ISSUE THREAD

**Issue by JBlaschke** [mpi4py/mpi4py#566] opened 2024-10-14 02:38 UTC
Is there a way to check which build flags where used? I used to use `mpi4py.get_config` to check the `mpicc` record for the "correct" mpi compiler. This seems to be blank now.

As a workaround I've been running `ldd /path/to/MPI.<whatever>.so` -- and checking for the correct libmpi -- but this is ugly, and brittle. Ideally I would like something like Julia's [`MPIPreferences.jl`](https://juliaparallel.org/MPI.jl/stable/reference/mpipreferences/) where I can just query the mpi configuration.

**Comment by JBlaschke** [comment] 2024-10-14 02:41
I also noted that if I build mpi4py a non-standard mpicc (by setting `MPICC`) then `mpi4py.get_config` still returns an empty dictionary....

**Comment by dalcinl** [comment] 2024-10-14 06:48
Duplicate of #532 (pinned issue at the top of https://github.com/mpi4py/mpi4py/issues). Please look at the full discussion there, and add your comments.

I'm not familiar with the low-level details of the Julia wrappers, but they definitely use a different model than mpi4py, with Julia based on dynamic loading. You can still figure out info about the underlying implementation using `mpi4py.MPI.get_vendor()`, but that's just name and version, and not lower level things like installation path and shared library name and location. The location of the MPI shared library can be found with some convoluted code using `ctypes` I posted here https://github.com/mpi4py/mpi4py/issues/532#issuecomment-2286827876.

**Closed** 2024-10-14 13:44 UTC
Labels: duplicate
