### ISSUE TITLE
Test failures on openSUSE i586

### ISSUE THREAD

**Issue by danigm** [mpi4py/mpi4py#279] opened 2022-11-10 11:36 UTC
Trying to build the latest release for openSUSE, I'm getting this error just in x86 arch:

```
[  191s] + /usr/lib/mpi/gcc/openmpi4/bin/mpiexec --use-hwthread-cpus --mca btl tcp,self -n 1 python3.8 -B test/runtests.py -v '--exclude=test_spawn|test_io'
[  192s] [0@lamb60] Python 3.8 (/usr/bin/python3.8)
[  192s] [0@lamb60] MPI 3.1 (Open MPI 4.1.4)
[  192s] [0@lamb60] mpi4py 3.1.4 (/home/abuild/rpmbuild/BUILDROOT/python-mpi4py-3.1.4-1.2.i386/usr/lib/python3.8/site-packages/mpi4py)
[  192s] --------------------------------------------------------------------------
[  192s] The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
[  192s] Workarounds are to run on a single node, or to use a system with an RDMA
[  192s] capable network such as Infiniband.
[  192s] --------------------------------------------------------------------------
[  192s] Traceback (most recent call last):
[  192s]   File "test/runtests.py", line 290, in <module>
[  192s]     sys.exit(main())
[  192s]   File "test/runtests.py", line 279, in main
[  192s]     testsuite = load_tests(options, args)
[  192s]   File "test/runtests.py", line 216, in load_tests
[  192s]     module = __import__(testname)
[  192s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/test_cco_buf.py", line 3, in <module>
[  192s]     import arrayimpl
[  192s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/arrayimpl.py", line 244, in <module>
[  192s]     import dlpackimpl as dlpack
[  192s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/dlpackimpl.py", line 187, in <module>
[  192s]     def dl_managed_tensor_deleter(void_p):
[  192s] MemoryError
[  192s] --------------------------------------------------------------------------
[  192s] Primary job  terminated normally, but 1 process returned
[  192s] a non-zero exit code. Per user-direction, the job has been aborted.
```

Full log can be found here: https://paste.opensuse.org/view/raw/83017332

**Comment by dalcinl** [comment] 2022-11-10 11:58
The code in `test/dlpackimpl.py` is not really related to MPI, it is just a pure-Python piece of code using ctypes to emulate the DLPack buffer exchange mechanism. I'm not sure why importing that code fails, but prima facie looks like some issue (in ctypes) unrelated to mpi4py.

PS: I'm having a few test regressions in Fedora 36 when using latest release, I'm investigating.

**Comment by dalcinl** [comment] 2022-11-10 12:15
Can you try:
```
rm test/dlpackimpl.py
```
before running the testsuite ?

**Comment by danigm** [comment] 2022-11-10 13:15
> Can you try:
> 
> ```
> rm test/dlpackimpl.py
> ```
> 
> before running the testsuite ?

Removing that file I've less tests failing, now I don't get the `MemoryError` but a different one that maybe it's a different issue:

```
[   17s] + /usr/lib/mpi/gcc/openmpi4/bin/mpiexec --use-hwthread-cpus --mca btl tcp,self -n 1 python3.10 -B test/runtests.py -v '--exclude=test_spawn|test_io'
[   17s] [0@localhost.localdomain] Python 3.10 (/usr/bin/python3.10)
[   17s] [0@localhost.localdomain] MPI 3.1 (Open MPI 4.1.4)
[   17s] [0@localhost.localdomain] mpi4py 3.1.4 (/home/abuild/rpmbuild/BUILDROOT/python-mpi4py-3.1.4-0.i386/usr/lib/python3.10/site-packages/mpi4py)
[   18s] --------------------------------------------------------------------------
[   18s] The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
[   18s] Workarounds are to run on a single node, or to use a system with an RDMA
[   18s] capable network such as Infiniband.
[   18s] --------------------------------------------------------------------------
[   18s] [localhost.localdomain:01971] mca_sharedfp_sm_file_open: Error, unable to mmap file: /tmp/ompi.localhost.399/pid.1967/1/mpi4py-0z59bmgw3_cid-1-1971.sm
[   18s] [localhost.localdomain:01971] Bad address
[   18s] Traceback (most recent call last):
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/runtests.py", line 290, in <module>
[   18s]     sys.exit(main())
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/runtests.py", line 279, in main
[   18s]     testsuite = load_tests(options, args)
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/runtests.py", line 216, in load_tests
[   18s]     module = __import__(testname)
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/test_file.py", line 189, in <module>
[   18s]     have_feature()
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/test_file.py", line 186, in have_feature
[   18s]     case.setUp()
[   18s]   File "/home/abuild/rpmbuild/BUILD/mpi4py-3.1.4/test/test_file.py", line 19, in setUp
[   18s]     self.FILE = MPI.File.Open(self.COMM,
[   18s]   File "mpi4py/MPI/File.pyx", line 95, in mpi4py.MPI.File.Open
[   18s] mpi4py.MPI.Exception: MPI_ERR_OTHER: known error not in list
[   18s] --------------------------------------------------------------------------
[   18s] Primary job  terminated normally, but 1 process returned
```

**Comment by dalcinl** [comment] 2022-11-10 14:14
> but a different one that maybe it's a different issue:

Well, you are running Open MPI... you already excluded `test_io`, perhaps you should also exclude `test_file`.

**Comment by dalcinl** [comment] 2022-11-18 16:00
@danigm I'll assume this issue is resolved. Closing.

**Closed by dalcinl** 2022-11-18 16:00 UTC
