### ISSUE TITLE
Print MPI information 

### ISSUE THREAD

**Issue by mtagliazucchi** [mpi4py/mpi4py#567] opened 2024-10-14 13:33 UTC
Hi all. 
I used to check the installation of `mpi4py` by printing the output of "mpi4py.get_config()" and checking if it was linked to the correct `MPI` library.
However, according to the [documentation](https://mpi4py.readthedocs.io/en/4.0.0/mpi4py.html) of version `>4.0.0`, this command returns an empty dictionary by default.

It is not clear to me how to check that `mpi4py` is linked to the correct `MPI` library in the new version.

**Comment by dalcinl** [comment] 2024-10-14 13:43
Duplicate of #532, which is a pinned issue at the top of of https://github.com/mpi4py/mpi4py/issues.
You can still use `mpi4py.MPI.get_vendor()`. It is not as informative, but it will allow to distinguish incompatible implementations like MPICH and Open MPI.  You could also run in the command line the following two commands
```console
python -m mpi4py --mpi-lib-version
ldd $(python -m mpi4py --prefix)/MPI.*.so
```

**Closed by dalcinl** 2024-10-14 13:43 UTC
