### ISSUE TITLE
cannot terminate MPI application

### ISSUE THREAD

**Issue by andre-merzky** [mpi4py/mpi4py#290] opened 2023-01-06 12:02 UTC
My MPI application seems to be unable to terminate if any of it's ranks fail.  From [here](https://github.com/chainer/chainermn/issues/236) I learned about a workaround which helps, but I still face the same problem if the `mpi4py` code is one fork down in the process chain.

Reproducer `t.py`:
```py
#!/usr/bin/env python3

import sys

# Global error handler
def global_except_hook(exctype, value, traceback):
    import sys
    try:
        import mpi4py.MPI
        sys.stderr.write("\n*****************************************************\n")
        sys.stderr.write("Uncaught exception was detected on rank {}. \n".format(
            mpi4py.MPI.COMM_WORLD.Get_rank()))
        from traceback import print_exception
        print_exception(exctype, value, traceback)
        sys.stderr.write("*****************************************************\n\n\n")
        sys.stderr.write("\n")
        sys.stderr.write("Calling MPI_Abort() to shut down MPI processes...\n")
        sys.stderr.flush()
    finally:
        try:
            import mpi4py.MPI
            mpi4py.MPI.COMM_WORLD.Abort(1)
        except Exception as e:
            sys.stderr.write("*****************************************************\n")
            sys.stderr.write("Sorry, we failed to stop MPI, this process will hang.\n")
            sys.stderr.write("*****************************************************\n")
            sys.stderr.flush()
            raise e


sys.excepthook = global_except_hook


def func():
    import time
    from mpi4py import MPI

    world = MPI.COMM_WORLD
    rank  = world.rank

    print(' = ', rank)

    if rank == 0:
        print(' - ', rank)
        raise RuntimeError('oops')

    while True:
        print(' + ', rank)
        time.sleep(1)
        world.Barrier()


if __name__ == '__main__':
    func()
```

Running `mpiexec -n 4 t.py` works as expected:
```sh
$ mpiexec -n 2 /tmp/t.py
 =  0
 -  0
 =  1
 +  1

*****************************************************
Uncaught exception was detected on rank 0. 
Traceback (most recent call last):
  File "/tmp/t.py", line 54, in <module>
    func()
  File "/tmp/t.py", line 45, in func
    raise RuntimeError('oops')
RuntimeError: oops
*****************************************************

Calling MPI_Abort() to shut down MPI processes...
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
$ 
```

but running the same in a subshell after the mpiexec results in the same output and infinite hang:
```sh
$ mpiexec -n 2 sh -c '/tmp/t.py'
 =  1
 +  1
 =  0
 -  0

*****************************************************
Uncaught exception was detected on rank 0. 
Traceback (most recent call last):
  File "/tmp/t.py", line 54, in <module>
    func()
  File "/tmp/t.py", line 45, in func
    raise RuntimeError('oops')
RuntimeError: oops
*****************************************************

Calling MPI_Abort() to shut down MPI processes...
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Strace shows that the mpiexec propcess is hanging on some select call:
```sh
$ s strace -f -p 12772
[sudo] password for merzky: 
strace: Process 12772 attached with 5 threads
[pid 12786] select(16, [13 15], NULL, NULL, {tv_sec=3544, tv_usec=141885} <unfinished ...>
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=0, tv_usec=178624} <unfinished ...>
[pid 12783] select(12, [10 11], NULL, NULL, {tv_sec=3544, tv_usec=107010} <unfinished ...>
[pid 12784] epoll_wait(16,  <unfinished ...>
[pid 12772] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 12785] <... select resumed> )      = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 12785] select(24, [22 23], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
...
```

The remaining rank loops on a poll:
```
xxxxx   12790     1 99 12:57 pts/12   00:02:07 python3 /tmp/t.py

$ s strace -f -p 12790
strace: Process 12790 attached with 3 threads
strace: [ Process PID=12790 runs in x32 mode. ]
[pid 12794] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 12793] epoll_wait(7, strace: [ Process PID=12790 runs in 64 bit mode. ]
 <unfinished ...>
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
[pid 12790] poll([{fd=5, events=POLLIN}, {fd=18, events=POLLIN}], 2, 0) = 0 (Timeout)
...
```

I would appreciate any advise on how to handle this.  The actual software stack is much more involved - it will not be possible to remove the intermediate process layer.

**Comment by eirrgang** [comment] 2023-01-06 12:31
Can you provide more environment information? I was not able to reproduce the hang with
* mpi4py 3.1.4
* mpiexec (OpenRTE) 4.0.3
* gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
* Python 3.9.5

**Comment by andre-merzky** [comment] 2023-01-06 14:04
Right, I should have provided that:

  - mpi4py 3.1.4
  - mpiexec (OpenRTE) 2.1.1
  - gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  - Python 3.6.9

**Comment by dalcinl** [comment] 2023-01-08 07:24
@andre-merzky Are you aware of the [documented solution](https://mpi4py.readthedocs.io/en/stable/mpi4py.run.html) for your issue?  Please take a look, it is much easier than rolling your own exception hook. That being said, if your `mpiexec` command is not behaving properly on calls to `MPI_Abort`, there is very little mpi4py can do.

**Comment by eirrgang** [comment] 2023-01-08 12:54
I was able to reproduce the hang in the `ubuntu:18.04` docker image, prepared with
```
apt-get update
apt-get install python3.6 python3-mpi4py vim rsh-client
```
and
```
mpiexec -n 4 --allow-run-as-root  sh -c /tmp/t.py
```

Something about this particular software stack apparently doesn't allow the abort-related details to correctly propagate up from the caller of MPI_Abort and down to the child process of `sh` in the other spawned process trees. Maybe there was an ORTE issue if the COMM_WORLD process group at MPI_Init didn't match the expected process IDs spawned by mpiexec? I couldn't find a specific bug (with just some quick googling) but it seems to be resolved in more recent software.

Note that the `apt` packages install mpi4py 2. For mpi4py 3.1.4, I also `apt-get install libopenmpi-dev python3-pip` and `pip install mpi4py`, instead. However, the `mpi4py.run` in v3.1.4 is also unable to successfully abort subprocesses, even with
```
mpiexec -n 2 --allow-run-as-root sh -c "python3 -m mpi4py /tmp/t.py"
```
with the custom exception handler removed.

I have not tried a more minimal example with just a C program because the apparent dependence on execution environment implies that this is not an mpi4py issue.

**Comment by andre-merzky** [comment] 2023-01-08 16:36
Thanks for the reply @dalcinl !  Alas, I see the same problem with the documented workaround:

```sh
$ mpiexec -n 4 sh -c 'python3 -m mpi4py ./t.py'
 =  0
 -  0
 =  3
 +  3
 =  2
 +  2
 =  1
 +  1

*****************************************************
Uncaught exception was detected on rank 0. 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ve_raptor/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/tmp/ve_raptor/lib/python3.6/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/tmp/ve_raptor/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./t.py", line 54, in <module>
    func()
  File "./t.py", line 45, in func
    raise RuntimeError('oops')
RuntimeError: oops
*****************************************************

Calling MPI_Abort() to shut down MPI processes...
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Also thanks @eirrgang : alas, we don't always have control over how mpi4py is being installed by our end users - but I'll give different stacks a try, if we are lucky it is a rare problem...

**Comment by dalcinl** [comment] 2023-01-09 01:27
@andre-merzky You should report your findings to Open MPI developers.

**Closed by dalcinl** 2023-01-09 01:27 UTC
